version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          name: "Install NVM"
      - run:
          command: nvm install --lts && nvm use --lts
          name: "Setup Node"
      - run:
          command: node -v
          name: "Node version"
      - run:
          command: npm run build
          name: "Build library"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          name: "Install NVM"
      - run:
          command: nvm install --lts && nvm use --lts
          name: "Setup Node"
      - run:
          command: npm run test
          name: "Run tests"
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  run-tests:
    jobs:
      - build
      - test
