version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build:
    docker:
      - image: cimg/node:22.3.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: node -v
          name: "Node version"
      - run:
          command: npm install
          name: "Install packages"
      - run:
          command: npm run build
          name: "Build library"
  test:
    docker:
      - image: cimg/node:22.3.0
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true
      - run:
          command: npm install
          name: "Install packages"
      - run:
          command: npm run test
          name: "Run tests"
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  run-tests:
    jobs:
      - build
      - test
