version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build-and-test:
    docker:
        - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: nvm install --lts && nvm use --lts
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: "Build library"
      - run:
          command: npm run test
          name: "Run tests"
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  run-tests:
    jobs:
      - build-and-test
