import * as Components from ".";

export type AnyComponent =
  | Components.Addition
  | Components.Advertisements.ReplicaAdvertisement
  | Components.ArticleStructure.ArticleLink
  | Components.ArticleStructure.Aside
  | Components.ArticleStructure.Chapter
  | Components.ArticleStructure.Container
  | Components.ArticleStructure.Divider
  | Components.ArticleStructure.FlexibleSpacer
  | Components.ArticleStructure.Header
  | Components.ArticleStructure.LinkButton
  | Components.ArticleStructure.Section
  | Components.AudioAndVideo.Audio
  | Components.AudioAndVideo.EmbedWebVideo
  | Components.AudioAndVideo.Music
  | Components.AudioAndVideo.Video
  | Components.AudioAndVideo.Podcast
  | Components.AugmentedReality.ARKit
  | Components.GalleriesAndMosaics.Gallery
  | Components.GalleriesAndMosaics.Mosaic
  | Components.Images.ArticleThumbnail
  | Components.Images.Figure
  | Components.Images.Image
  | Components.Images.Logo
  | Components.Images.Photo
  | Components.Images.Portrait
  | Components.Location.Map
  | Components.Location.Place
  | Components.SocialMedia.SocialMediaComponent
  | Components.SocialMedia.FacebookPost
  | Components.SocialMedia.Instagram
  | Components.SocialMedia.TikTok
  | Components.SocialMedia.Tweet
  | Components.Tables.DataTable
  | Components.Tables.HTMLTable
  | Components.Text.ArticleTitle
  | Components.Text.Author
  | Components.Text.Body
  | Components.Text.Byline
  | Components.Text.Caption
  | Components.Text.ConditionalText
  | Components.Text.Heading
  | Components.Text.Illustrator
  | Components.Text.Intro
  | Components.Text.Photographer
  | Components.Text.PullQuote
  | Components.Text.Quote
  | Components.Text.Title;
